FROM dare-dispel4py:latest

ENV ICCLIM_VERSION 4.2.13

RUN pip install netCDF4
RUN conda install -c conda-forge netcdftime

RUN wget https://github.com/cerfacs-globc/icclim/archive/${ICCLIM_VERSION}.tar.gz && \
    tar xzf ${ICCLIM_VERSION}.tar.gz && \
    cd icclim-${ICCLIM_VERSION}/ && \
    gcc -fPIC -g -c -Wall ./icclim/libC.c -o ./icclim/libC.o && \
    gcc -shared -o ./icclim/libC.so ./icclim/libC.o && \
    python setup.py install
