name: Regression test (MPI mapping)

on:
  push:
    branches:
      - main

jobs:
  regression-test-multi:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Set up directory structure
        run: |
          mkdir dispel4py # New version
          mkdir dispel4py_autoscaling # old version
          tree -L 2
          
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          path: ./dispel4py
          
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1

      - name: Setup Python 3.10.13 for current repo
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13

      - name: Setup venv for the current project
        working-directory: ./dispel4py
        run: |
          python3.10 -m venv venv
          source venv/bin/activate
          pip install -r ./requirements.txt

      - name: Checkout old dispel4py repo
        uses: actions/checkout@v2
        with:
          path: ./dispel4py_autoscaling
          repository: NoPuzzle/dispel4py_autoscaling # Could also try comparing with old dispel4py (Python 2)

      - name: Setup Python 3.7 for old dispel4py repo
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup venv for the old version of dispel4py
        working-directory: ./dispel4py_autoscaling
        run: |
          python3.7 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install mpi4py

      - name: Test multi mapping for this version of dispelpy
        run: |
          cd dispel4py
          source venv/bin/activate
          mpirun -np 10 python -m dispel4py.new.processor dispel4py.new.mpi_process dispel4py.examples.graph_testing.pipeline_test -i 20 -n 10  > output_new_mpi.txt
          deactivate

      - name: Test multi mapping for old version of dispelpy
        run: |
          cd dispel4py_autoscaling
          source venv/bin/activate
          mpirun -np 10 python -m dispel4py.new.processor dispel4py.new.mpi_process dispel4py.examples.graph_testing.pipeline_test -i 20 -n 10 > output_old_mpi.txt
          deactivate

      - name: Diff outputs for mpi mapping
        run: |
          diff -y <(grep -v '^ELAPSED TIME' dispel4py_autoscaling/output_old_mpi.txt) <(grep -v '^ELAPSED TIME' dispel4py/output_new_mpi.txt)
